### ISSUE TITLE
not updating containers

### ISSUE THREAD

**Issue by delanym** [bcicen/ctop#187]
After a while, the list of containers shown in ctop doesn't match `docker stats`
Can't provide much more than that at the moment.

ctop version 0.7.2, build 70bd2ae go1.11.3
Docker version 18.09.7, build 2d0083d
Ubuntu 18.04.3 LTS

**Comment by gautaz** [comment]
I face the same issue from time to time.

**Comment by bcicen** [comment]
Thanks for the details -- are you still seeing removed containers in the view, missing new containers, both?

**Comment by delanym** [comment]
Missing new containers.

**Comment by dpieski** [comment]
Second the missing containers. Had to restart the ctop container to view all containers again
Docker version 19.03.5, build 633a0ea
GOLANG_VERSION=1.12.1
ctop version: quay.io/vektorlab/ctop:latest (which should be v 0.7.3)

**Comment by timwhite** [comment]
Still having the issue with ctop:latest docker image (id f965f5a1fff8)

**Comment by stokito** [comment]
I *guess* this may happen because ctop is not capturing all events:
In the connector/docker.go:64 we have:
```go
		case "start", "die", "oom", "pause", "unpause", "health_status":
			log.Debugf("handling docker event: action=%s id=%s", e.Action, e.ID)
			cm.needsRefresh <- e.ID
		case "destroy":
			log.Debugf("handling docker event: action=%s id=%s", e.Action, e.ID)
			cm.delByID(e.ID)
		}
```
So the container will be refreshed only on few events. In the same time there is a lot of others: `attach, commit, copy, create, detach, exec_create, exec_detach, exec_start, export, kill, oom, rename, resize, restart, stop, top, update`.
For example when container is OOMKilled then here we'll have `oom` event.
I'm not sure, but maybe this is a reason why some containers aren't updated.

**Comment by stokito** [comment]
Events may lost so we need to refresh all information periodically.
