### ISSUE TITLE
Text color on light background

### ISSUE THREAD

**Issue by steveb** [bcicen/ctop#41]
The main text color doesn't display well on light backgrounds, see attached
![screenshot from 2017-03-15 09-47-47](https://cloud.githubusercontent.com/assets/48336/23921735/9730a0fa-0964-11e7-9e8c-b4aff1a27608.png)

**Comment by bcicen** [comment]
`-i` option for inverted foreground colors is added in the [latest release](https://github.com/bcicen/ctop/releases/latest)

**Comment by steveb** [comment]
Brilliant, thanks

**Comment by callumgare** [comment]
How does htop and other commands automatically show the right coloured text for the terminal theme? Is it possible to do that for this rather than having to manually set a flag? My terminal is set to be light during the day and automatically change to a dark theme after sunset and it's a bit annoying having to always think about whether to set an invert flag or not.
