### ISSUE TITLE
Memory displaying 0B / 0B

### ISSUE THREAD

**Issue by sgreenslade** [bcicen/ctop#45]
Hi,

Great tool thanks. Works fine natively on my mac fine.

However when installed on an ESX VM running docker containers the CPU, NET and ID are all reported, but the Memory column displays 0B / 0B and the PIDS column displays 0
My ESX VM:
- Debian GNU/Linux 8 (jessie)
- Docker 1.13.0
- Kernel: 3.16.0-4-amd64

Any idea why the memory and PIDS are not reported?
Thanks.

**Comment by markhilton** [comment]
In order to support Docker memory limits / quotas you need to enable:

cgroup_enable=memory swapaccount=1

Linux kernel command line options on my Debian Jessie Google Cloud Compute Engine instances. 
Update /etc/default/grub and set:

GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
run update-grub && reboot

**Comment by sgreenslade** [comment]
Many thanks Mark,

Those changes worked for me on my ESX machine.
